services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./citation-network-backend:/app
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/citations_data.db

networks:
  default:
    driver: bridge